### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by deanfourie1** [Nerwyn/material-rounded-theme#19]
**Is your feature request related to a problem? Please describe.**
Can you please provide examples of the cards shows in the images?

**Describe the solution you'd like**
an examples YAML or something?

**Describe alternatives you've considered**
?

**Additional context**
Nothing, again just examples for the card styles shown in the example images. Thanks

**Comment by Nerwyn** [comment]
Any ones in particular? They're mostly basic Home Assistant cards.
[The README talks about Big Slider Card](https://github.com/Nerwyn/material-rounded-theme?tab=readme-ov-file#big-slider-card) and includes the style options needed to make it match the screenshots.

Section headers are made using [button card](https://github.com/custom-cards/button-card), but mine don't exactly match the Google Home ones.
```yaml
type: custom:button-card
name: Security
icon: mdi:shield-key
layout: icon_name
styles:
  card:
    - background-color: rgb(0, 0, 0, 0)
    - padding: 4px 20px
  icon:
    - height: 20px
    - width: 32px
    - padding-bottom: 3px
  name:
    - font-weight: 500
    - font-size: 18px
    - text-align: left
  grid:
    - grid-template-columns: min-content min-content
```

Half of the tiles use my project [Service Call Tile Feature](https://github.com/Nerwyn/service-call-tile-feature) for custom tile features, not limited to service calls.
