### ISSUE TITLE
Issue with 2024.6/7 with new view 

### ISSUE THREAD

**Issue by MickLesk** [Nerwyn/material-rounded-theme#22]
**Checklist:**

-   [x] I updated to the latest version available
-   [x] I cleared the cache of my browser

**Release with the issue:**
2024.6 | Now 2024.7
**Last working release (if known):**
2024.5 (before new experimental views)

**Browser and Operating System:**
Chrome, Firefox, Windows & Linux.
Smartphone too. All Newest Versions

**Description of problem:**
The new sections have been set up in the new version of Homeassistant.
These new sections directly define how many elements fit next to each other. 
There are "headings" for these sections, which saves you additional entities / elements.

These headings are completely removed with the Material Round Design and the view is moved to the top

Pic 1: 
Other Theme (Google Theme) - Headings visible:
![image](https://github.com/Nerwyn/material-rounded-theme/assets/47820557/40f35795-863d-4b40-a776-887b2231e261)

Pic 2: 
Material Theme - Headings invisible, all moved up
![image](https://github.com/Nerwyn/material-rounded-theme/assets/47820557/84b79a84-3bc4-4378-ad6d-ab14febbdcbf)

Only the Material Theme (No Mods) works. 
Is that how it should be? If so, feel free to close the bug

**Javascript errors shown in the web inspector (if applicable):**
No Problem.

**Additional information:**

**Comment by Nerwyn** [comment]
Is this with the theme set at the card level? I can't seem to recreate the issue with the theme at the user, view, or card level. I updated my dashboards to sections and the titles appear.

![image](https://github.com/Nerwyn/material-rounded-theme/assets/43071698/3a673093-7333-4d0e-8bab-d7b41c2761d2)

Maybe try clearing cache?

**Comment by MickLesk** [comment]
Here are my Settings of the Entry:
![image](https://github.com/Nerwyn/material-rounded-theme/assets/47820557/d218f1a6-88d2-4fe4-a86e-39e0112d1feb)

The single cards dont have any other theme (use the settings from main entry) 

Here is the full code of the dashboard entry:


> - title: Formentor
>     path: formentor
>     type: sections
>     sections:
>       - type: grid
>         cards:
>           - show_state: true
>             show_name: true
>             camera_view: auto
>             type: picture-entity
>             entity: device_tracker.******
>             image: >-
>               https://carvo.ch/assets/images/models/md-221/original/cupra-formentor-20-tsi-4drive-fs12KUNuaf.png
>           - type: map
>             entities:
>               - entity: device_tracker.******
>             dark_mode: false
>             title: Formentor Standort
>             aspect_ratio: '16:9'
>             default_zoom: 14
>             auto_fit: true
>             hours_to_show: 96
>             entity_picture: local/pictures/cupra.svg
>         title: Formentor
>       - type: grid
>         cards:
>           - graph: line
>             type: sensor
>             entity: sensor.******
>             detail: 1
>             hours_to_show: 336
>             name: Service
>             icon: mdi:car-clock
>             unit: Tage
>             layout_options:
>               grid_columns: 4
>               grid_rows: 3
>           - graph: line
>             type: sensor
>             entity: sensor.******
>             detail: 1
>             hours_to_show: 336
>             name: Ölwechsel
>             icon: mdi:oil
>             unit: Tage
>             layout_options:
>               grid_columns: 2
>               grid_rows: 3
>           - graph: line
>             type: sensor
>             entity: sensor.******
>             detail: 1
>             hours_to_show: 336
>             name: Ölwechsel in km
>             icon: mdi:oil-level
>             unit: km
>             layout_options:
>               grid_columns: 2
>               grid_rows: 3
>         title: Service-Themen
>       - type: grid
>         cards:
>           - type: entities
>             entities:
>               - entity: binary_sensor.formentor_door_closed_left_back
>                 name: Tür hinten Links
>               - entity: binary_sensor.formentor_door_closed_right_front
>                 name: Tür vorne Rechts
>               - entity: binary_sensor.formentor_door_closed_left_front
>                 name: Tür vorne Links
>               - entity: binary_sensor.formentor_door_closed_right_back
>                 name: Tür hinten Rechts
>           - type: gauge
>             entity: sensor.formentor_combustion_range
>             name: Reichweite
>             needle: true
>             max: 650
>             severity:
>               green: 450
>               yellow: 200
>               red: 0
>             min: 0
>             unit: km
>         title: Status
>     max_columns: 3
>     cards: []
>     icon: phu:cupra
>     theme: Material Rounded
>     subview: false

**Comment by Nerwyn** [comment]
Can you fix your config formatting? Wrap it in a code block Like this

\```yaml
Your config here
\```

**Comment by MickLesk** [comment]
Oh sorry :-D

```yaml
  - title: Formentor
    path: formentor
    type: sections
    sections:
      - type: grid
        cards:
          - show_state: true
            show_name: true
            camera_view: auto
            type: picture-entity
            entity: device_tracker.******
            image: >-
              https://carvo.ch/assets/images/models/md-221/original/cupra-formentor-20-tsi-4drive-fs12KUNuaf.png
          - type: map
            entities:
              - entity: device_tracker.******
            dark_mode: false
            title: Formentor Standort
            aspect_ratio: '16:9'
            default_zoom: 14
            auto_fit: true
            hours_to_show: 96
            entity_picture: local/pictures/cupra.svg
        title: Formentor
      - type: grid
        cards:
          - graph: line
            type: sensor
            entity: sensor.******
            detail: 1
            hours_to_show: 336
            name: Service
            icon: mdi:car-clock
            unit: Tage
            layout_options:
              grid_columns: 4
              grid_rows: 3
          - graph: line
            type: sensor
            entity: sensor.******
            detail: 1
            hours_to_show: 336
            name: Ölwechsel
            icon: mdi:oil
            unit: Tage
            layout_options:
              grid_columns: 2
              grid_rows: 3
          - graph: line
            type: sensor
            entity: sensor.******
            detail: 1
            hours_to_show: 336
            name: Ölwechsel in km
            icon: mdi:oil-level
            unit: km
            layout_options:
              grid_columns: 2
              grid_rows: 3
        title: Service-Themen
      - type: grid
        cards:
          - type: entities
            entities:
              - entity: binary_sensor.******
                name: Tür hinten Links
              - entity: binary_sensor.******
                name: Tür vorne Rechts
              - entity: binary_sensor.******
                name: Tür vorne Links
              - entity: binary_sensor.******
                name: Tür hinten Rechts
          - type: gauge
            entity: sensor.******
            name: Reichweite
            needle: true
            max: 650
            severity:
              green: 450
              yellow: 200
              red: 0
            min: 0
            unit: km
        title: Status
    max_columns: 3
    cards: []
    icon: phu:cupra
    theme: Material Rounded
    subview: false
```

**Comment by Nerwyn** [comment]
I'm still seeing the headings
![image](https://github.com/Nerwyn/material-rounded-theme/assets/43071698/a71d38e1-17ec-4711-bd10-a6adb9c8b5a5)
I think you may be having some larger issues based on your screenshots. The toolbar in them is green, at the top of the page, and doesn't have the styling from this theme.

**Comment by MickLesk** [comment]
I have now deleted a lot of "themes" and other useless stuff. That didn't help. However, I noticed that when I made your theme the default theme for my user, 2 other dashboards ( of 4) worked. 
I looked at the code and found the problem (might be worth a doc update?)

The problem is the HACS frontend plugin: Keep Text in Tabs: 
https://github.com/elchininet/keep-texts-in-tabs
Row 1 - 3 

```yaml
title: Home
keep_texts_in_tabs:
  enabled: true
views:
  - title: Home
    path: default_view
    type: custom:masonry-layout
    icon: mdi:home
    ....
```
