### ISSUE TITLE
How to turn of the view names?

### ISSUE THREAD

**Issue by nightfever77** [Nerwyn/material-rounded-theme#3]
Great work, one question: How to turn off the view names? Did not found a clew in the card-mod section.
I am asking because they are overlaying in HA companion app.

**Comment by nightfever77** [comment]
Nevermind, just deleted the view names in the view editor

**Comment by Nerwyn** [comment]
I am adding a "no mod" version of the theme if you want to completely disable toolbar changes.

The bit of CSS that creates the labels is [here](https://github.com/Nerwyn/material-rounded-theme/blob/main/themes/material_rounded.yaml#L324-L331). While you could delete this, removing the names from the views as you did is a better solution that won't break with updates.

```css
paper-tab::after {
  content: attr(aria-label);
  text-transform: none;
  text-align: center;
  position: relative;
  top: -12px;
  font-weight: normal;
}
```

Also, how is it overlaying with the companion app? It doesn't for me on Android and iPhone.
