### ISSUE TITLE
Same Variable for Material You Color for different users

### ISSUE THREAD

**Issue by NikolasRupp** [Nerwyn/material-rounded-theme#32]
If you define multiple Material You colors by using the variables `sensor.material_rounded_base_color_name_1` & `sensor.material_rounded_base_color_name_2` is there a way to access the color via a variable or a sensor that has always the same name but has different colors depending on the user that is logged in.

For example i want to make a `custom:button_card` and want to have the material You color as background. Ist there a way so i can for example use
```
type: custom:button-card
entity: test.entity
styles:
  card:
    - background-color: var(--material-rounded-base-color)
```
and the color will change depending on the user that is logged in
