### ISSUE TITLE
Background is not correct colour when using bubble card popups

### ISSUE THREAD

**Issue by iamthekings5** [Nerwyn/material-rounded-theme#36]
**Checklist:**

-   [/] I updated to the latest version available
-   [/] I cleared the cache of my browser

**Release with the issue: v2.1.5**

**Last working release (if known):**

**Browser and Operating System: Home Assistant Android Companion App Android 14 OneUI 6.1**

**Description of problem:**

When using Bubble Card popups linked to a vertical stack, the background is not white or black on the light theme and dark theme respectively. It uses what I think is the accent colour, light blue and grey respectively.

![Screenshot_20241023_104004_Home Assistant.png](https://github.com/user-attachments/assets/d9d58a4c-3c63-4668-80a7-69dfb48cc57c)

![Screenshot_20241023_103933_Home Assistant.png](https://github.com/user-attachments/assets/239f8443-3c47-41b4-92f5-0910e280de1b)

I believe the correct implementation should be a white or black background depending on the theme.

If this cannot be changed could you please suggest where I can get this pop up features from elsewhere that works with material rounded theme.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by Nerwyn** [comment]
Bubble card's popup background color is computed using the theme card background color, so it's always a slightly different color with a little bit of transparency. Because the card border is transparent in this theme, it makes it hard to distinguish between the card and the popup background. This isn't a bug with this theme, it's clashing style decisions between it and popup card. There's nothing to be done about it here, you have to change the bubble card popup background using it's built in style options.

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#test"
    bg_color: var(--lovelace-background)
  - type: tile
    entity: light.sunroom_ceiling
    features:
      - type: light-brightness
```
