### ISSUE TITLE
More fleshed out documentation, please?

### ISSUE THREAD

**Issue by doubleangels** [Nerwyn/material-rounded-theme#6]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Could we get a little more documentation on how to use the theme? It took me a while to figure out that it's a dashboard theme and not a card theme, for example. Could we get some more sample code for the light cards you show in your screenshots? An example dashboard, essentially. :)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Nerwyn** [comment]
I don't understand how you would confuse this for a card theme. The README has screenshots of the dashboard, talks about modifying the dashboard toolbar, and has instructions on how to install it which includes enabling it as a global theme.

There's already example code in the README for the [big slider card](https://github.com/nicufarmache/lovelace-big-slider-card) lights:

```yaml
colorize: true
show_percentage: true
bold_text: true
height: 88
```

You should read the README in that repository for further information on setting up big slider card, but here's my full light card configurations:

```yaml
type: custom:big-slider-card
entity: light.kitchen_bar
name: Bar
colorize: true
show_percentage: true
height: 88
bold_text: true
card_mod:
  style: |
    :host {
      --card-mod-icon:
        {% if is_state(config.entity, "on") %}
        mdi:ceiling-light-multiple;
        {% else %}
        mdi:ceiling-light-multiple-outline;
        {% endif %}
    }
```

And for lights without brightness control:

```yaml
type: custom:big-slider-card
entity: light.backyard_lights
name: Backyard
color: sandybrown
show_percentage: false
height: 88
bold_text: true
max: 0
card_mod:
  style: |
    :host {
      --card-mod-icon:
        {% if is_state(config.entity, "on") %}
        mdi:string-lights;
        {% else %}
        mdi:string-lights-off;
        {% endif %}
    }
```
