### ISSUE TITLE
Top Bar

### ISSUE THREAD

**Issue by novanatus** [Nerwyn/material-rounded-theme#66]
Is it possible to hide only the top bar in the mod version?

**Comment by Nerwyn** [comment]
Questions like this are better suited for the discussions section.

[Per the README](https://github.com/Nerwyn/material-rounded-theme?tab=readme-ov-file#developing-modifying-and-building-the-theme), if you want alternate card-mod modifications you need to modify the theme source CSS and rebuild it yourself.

You can set the following styles [in this file](https://github.com/Nerwyn/material-rounded-theme/blob/main/src/common/root.css#L40-L43) to hide the top app bar but still show the navigation bar.

```css
.toolbar {
  visibility: hidden;
}
ha-tabs {
  visibility: visible;
}
```

Doing this will hide the menu and action item buttons, which I wouldn't recommend. To also hide the top app bar title add these styles:

```css
paper-tab.iron-selected::before {
  visibility: hidden;
}
```
