### ISSUE TITLE
Bad contrast with Bubble Card since 3.1.3

### ISSUE THREAD

**Issue by Hammerpawn** [Nerwyn/material-rounded-theme#73]
**Checklist:**

-   [x] I updated to the latest version available
-   [x] I cleared the cache of my browser

**Release with the issue:** 3.1.3

**Last working release (if known):** 3.1.2

**Browser and Operating System:** Vivaldi on Windows (but it's a general thing)

**Description of problem:**

I just installed the latest version of this theme and I think #72 has caused some colors to change. I personally use Bubble Card for my whole dashboard and with the latest version the contrast of certain elements of my dashboard have gotten very bad. See below for two before vs. after examples:

**Before (3.1.2)**

![Image](https://github.com/user-attachments/assets/200e49e4-ef83-499d-aa39-95c4ac30f5ac)

**After (3.1.3)**

![Image](https://github.com/user-attachments/assets/65bc1b2d-3a54-4878-9452-9bf639837593)

**Before (3.1.2)**

![Image](https://github.com/user-attachments/assets/abd5aeda-4035-43c6-a203-4eba379fdc8f)

**After (3.1.3)**

![Image](https://github.com/user-attachments/assets/343b0588-f825-40c6-a0eb-c7352469bf06)

**Additional information:**

Not sure what the solution would be here as I can imagine changing it again implies breaking it for others. Maybe it would be nice to include some color settings in the configuration GUI in HA. Also fine with changing it somewhere manually, but you would have to tell me where to do this, because I don't know where to look.

PS: You have improved my Home Assistant experience so much with this theme. The whole application looks so sleek now. 🙌

**Comment by Nerwyn** [comment]
I was afraid something like this would happen 😬. In 3.1.3 I changed `--accent-color` from `--md-sys-color-on-primary` to `--md-sys-color-secondary` and `--text-accent-color` from `--md-sys-color-primary` to `--md-sys-color-on-secondary`, in order to fix an issue with [Home Assistant graph colors not being visible](https://github.com/Nerwyn/material-rounded-theme/issues/72#issuecomment-2761947456) without a card-mod fix.

Because the fix is for a default card, I don't think I can justify reverting it as it doesn't seem to break any other default UI elements. BUT Bubble Card has excellent built in style options we can use to fix this.

You can revert this change just for bubble cards within each bubble cards Custom styles / Templates field with the following style:

```css
:host {
  --bubble-accent-color: var(--md-sys-color-on-primary);
}
```

Actually, it wouldn't be the worst thing if I set this variable within the theme itself. Setting theme colors from the Home Assistant theme UI doesn't seem to be an option for custom themes. Otherwise I would have used it for the color sensor.

**Comment by Hammerpawn** [comment]
> I was afraid something like this would happen 😬.

Haha, I can imagine. 😛  But no worries, I completely understand the argument to keep it as is.

You pointed me in the right direction though! It's just that the style you posted only changed it for some sub-buttons. I think it might have something to do with the fact that for my main dashboard view I'm using [this room card styling module](https://github.com/Clooos/Bubble-Card/discussions/927#discussioncomment-12267029). I was able to fix it for all sub-buttons by using this in the style sections for those room cards.

```css
:host {
  --accent-color: var(--md-sys-color-on-primary);
}
``` 

Also, in my first screenshot you can see that the icon for my AC unit ('Airco') has this dark blue color which doesn't work well with the dark background. The 3.1.4 update changed that to the lighter color, so I'm keeping that. :) For anyone who also encountered this, the background color for the selected dropdown item can be changed by using the following style:

```css
:host {
  --bubble-select-list-item-accent-color: var(--md-sys-color-on-primary);
}
```

**Comment by Nerwyn** [comment]
I'm actually going through the Bubble Card README and Material Design 3 spec to add some of these Bubble Card specific colors to the theme, including `--bubble-select-list-item-accent-color`. I'll put out an alpha soon.

**Comment by Nerwyn** [comment]
@Hammerpawn try the 3.1.5 alpha. I've added the following based on the Bubble Card README and Material Design 3 specification:

```css
/*
 * Used for backgrounds behind text or icons
 * Inverted since the icons are not inverted
 * https://m3.material.io/components/icon-buttons/specs#d4169fb5-4cf8-40b6-9ec3-4044f09cca1f
 * */
--bubble-accent-color: var(--md-sys-color-inverse-primary)
--bubble-select-arrow-background-color: var(--md-sys-color-inverse-primary)

/* 
 * Used for dropdown selected option
 * https://m3.material.io/components/menus/specs#c811d2fa-469a-4e4e-9d9f-0f535c5c9b4c
 * */
--bubble-select-list-item-accent-color: var(--md-sys-color-secondary-container)
```

Let me know if you notice any other weird looking colors in Bubble Card.

**Comment by luckkmaxx** [comment]
Same here.
Using bar-card. `var(--accent-color)` now has a very light color.
`var(--md-sys-color-on-primary)` works, but only for this theme. No color in other themes.

**Comment by Hammerpawn** [comment]
@Nerwyn Nice, I like this color better than the dark purple. Works very well with the sliders as well!

I've been playing around with it and it seems like the only thing that still shows the weird color is when I add a sub-button that is a light entity. I don't encounter it with any other entity types. Here's an example:

**Light slider with a light entity as a sub-button**

<img width="511" alt="Image" src="https://github.com/user-attachments/assets/4e1a6531-3080-44de-a117-6d36356a3a27" />

**Climate card with dropdown sub-button listing the heating modes**

<img width="511" alt="Image" src="https://github.com/user-attachments/assets/142a985b-c688-4490-a1b1-30fbc8d91637" />

This is what it shows for both sub-buttons when I set `state_background` to`true`. I suspect the light sub-button is acting weird because of the `light_background` attribute. The light entity seems to be the only one to have that attribute.

```
type: custom:bubble-card
card_type: button
entity: light.chroomlamp
button_type: slider
force_icon: false
show_state: false
show_attribute: false
show_last_changed: false
slider_live_update: false
card_layout: large
sub_button:
  - entity: light.chroomlamp
    light_background: false
    show_last_changed: false
    show_last_updated: true
    show_name: false
    show_attribute: false
tap_action:
  action: toggle
double_tap_action:
  action: more-info
hold_action:
  action: more-info
grid_options:
  columns: 12
  rows: 1
modules:
  - default
use_accent_color: true
```

**Comment by Nerwyn** [comment]
It took me a bit to find the best/most appropriate colors to fix this but I've added a couple more Bubble Card colors that should make this look right.

```css
/*
 * This one was more tricky as by default it was using --md-sys-color-secondary-container, but that clashed with the sub button color
 * The MD3 slider spec wasn't very helpful either as it used the same colors
 * Instead I opted for a filled card background color, as it was similar to but distinct from card and lovelace background colors
 * https://m3.material.io/components/cards/specs#0f55bf62-edf2-4619-b00d-b9ed462f2c5a
 * */
--bubble-button-main-background-color: var(--md-sys-color-surface-container-highest)

/*
 * Filled tonal button
 * https://m3.material.io/components/buttons/specs#158f0a18-67fb-4ac4-9d22-cc4d1adc4579
 * */
--bubble-sub-button-light-background-color: var(--md-sys-color-secondary-container)
```

**Comment by Hammerpawn** [comment]
@Nerwyn Looks good! I also tested the light mode of your theme and for that it also works quite well.

<img width="475" alt="Image" src="https://github.com/user-attachments/assets/712ad1b0-31bc-47d0-9793-074ae36d9da8" />

The only remark I still have based on my testing is that the newest styling is implemented for the Bubble Card 'Button' card, but not for the other card types. This makes it look a bit inconsistent when you have multiple card types in one view:

<img width="540" alt="Image" src="https://github.com/user-attachments/assets/d62cfbd2-1976-488b-90ef-edb7b311018d" />

At the bottom I have added a 'Cover' (don't mind that it's unavailable) and 'Select' card and those don't have the same dark background as the 'Spotjes' and 'Chroomlamp' (which are Button cards). The climate card at the top by default also shows the same background color as the bottom ones, but I fixed it here manually with this code:

```css
:host {
  --bubble-climate-background-color: var(--md-sys-color-surface-container-highest),
}
``` 

I don't mind changing it for the other cards manually as well, but I think in the end it would be easiest if the same styling is used for all card types.

<img width="499" alt="Image" src="https://github.com/user-attachments/assets/bd84175a-b64f-4af2-b2b7-63a5cf42c4e5" />

**Comment by Nerwyn** [comment]
@Hammerpawn good catch. I could just set `--bubble-main-background-color` instead of `--bubble-button-main-background-color`, and that would catch all Bubble Card default backgrounds.

![Image](https://github.com/user-attachments/assets/32e410a7-91e5-40b0-b7ea-a3cb02ebefc3)

Try the latest alpha and thanks for the feedback!

**Comment by Hammerpawn** [comment]
@Nerwyn I think that what you shared in the pic looks amazing and I feel like we're very near to closing this issue! However, I installed the latest alpha and for some reason it looks like I'm back to where we started 😅 This is what I see currently:

![Image](https://github.com/user-attachments/assets/822775d6-a899-4aeb-a687-bfe77c772914)

I have all custom styling removed, tried removing and re-installing, clearing cache, but to no avail... It shows the same colors for all the other card types. The background is not the darker grey like in your pic.

Maybe it's something with the .yaml. If you can share it I can check if there's a difference with mine. Here's mine for the lights:

```
      - type: custom:bubble-card
        card_type: separator
        name: Lampen
        icon: mdi:lightbulb
        card_layout: large
        modules:
          - default
        styles: |-
          :host {
            --bubble-line-background-color: var(--md-sys-color-surface-container-highest),
          }
      - type: custom:bubble-card
        card_type: button
        entity: light.spotjes_zolder
        button_type: slider
        force_icon: false
        show_state: false
        show_attribute: false
        show_last_changed: false
        slider_live_update: false
        card_layout: large
        sub_button: []
        grid_options:
          columns: 12
          rows: 1
        tap_action:
          action: toggle
        double_tap_action:
          action: more-info
        hold_action:
          action: more-info
        modules:
          - default
        use_accent_color: true
        show_icon: true
        name: Spotjes
        styles: ""
      - type: custom:bubble-card
        card_type: button
        entity: light.chroomlamp
        button_type: slider
        force_icon: false
        show_state: false
        show_attribute: false
        show_last_changed: false
        slider_live_update: false
        card_layout: large
        sub_button:
          - entity: light.chroomlamp
            show_state: true
            show_last_changed: true
        tap_action:
          action: toggle
        double_tap_action:
          action: more-info
        hold_action:
          action: more-info
        grid_options:
          columns: 12
          rows: 1
        modules:
          - default
        use_accent_color: true
        styles: ""
        light_transition: false
      - type: custom:bubble-card
        card_type: button
        modules:
          - default
        entity: light.nachtlamp_nick
        use_accent_color: false
        force_icon: false
        sub_button:
          - entity: light.nachtlamp_nick
            show_state: true
            show_last_changed: true
        button_type: slider
```
