### ISSUE TITLE
Material You Theme Reverts to Default Color on App Restart (4.0.0-beta.014)

### ISSUE THREAD

**Issue by remcoenden** [Nerwyn/material-rounded-theme#78]
**Checklist:**

-   [X] I updated to the latest version available
-   [x] I cleared the cache of my browser

**Release with the issue:** 4.0.0-beta.014

**Last working release (if known):** N/A

**Browser and Operating System:** Homa Assistant Companion App, Android 15, Pixel 7 Pro

**Description of problem:**

After following the updated installation instructions from the Beta README for version 4.0.0-beta.014 of the Material Rounded Theme, the initial theme modifications and color automation appear to work as expected when the Home Assistant Companion App is active. Specifically:

- The app theme updates to reflect the specified color modifications.

- The automation, configured to adjust the theme based on the system accent color, functions correctly while the app is open.

However, when I close the Home Assistant app and then reopen it, the theme does not retain these modifications. Instead, it reverts to the default color scheme. It is only after manually opening the new Material You Theme tab within the app that the intended theme color is applied again. This cycle repeats with each app restart, requiring the tab to be opened to reinitialize the updated color scheme.

This behavior suggests that the theme settings or automation for updating the theme based on the system accent color are not persisting or automatically re-triggering when the app is reopened.

**Comment by remcoenden** [comment]
Hi, thanks for looking into this.

I can confirm I'm using an admin account, and I've set up the necessary helpers through the account tab. My Material You Base Color <USER> sensor is updating as expected based on the automation. I modified the example automation to update my user sensor instead of the generic one, as shown below:
```yaml
actions:
  - action: input_text.set_value
    metadata: {}
    data:
      value: "{{ states(\"sensor.pixel_7_pro_accent_color\") }}"
    target:
      entity_id: input_text.material_you_base_color_bdd95137411b4690b8e11fbc95e88087
```
The value of input_text.material_you_base_color_bdd95137411b4690b8e11fbc95e88087 does change in accordance with my phone's accent color, confirming that the automation is functioning correctly. Let me know if you need additional traces or further details from my end.

**Comment by remcoenden** [comment]
Thanks for the follow-up!

Here’s what my configuration.yaml currently looks like (some unrelated configuration has been removed for clarity):

```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/material-you-utilities.min.js

panel_custom:
  - name: material-you-panel
    url_path: material-you-configuration
    sidebar_title: Material You Theme
    sidebar_icon: mdi:material-design
    module_url: /local/material-you-utilities.min.js
```

The JavaScript module is locally installed and located at `/homeassistant/www/material-you-utilities.min.js`, and it is referenced both as a `frontend.extra_module_url` and as the `module_url` for the custom panel.

Let me know if there’s anything specific you’d like me to test or provide further!
